services:
  custom:
    env_file:
      - .env
    image: wonli/usersjs:${TAG}
    container_name: "wonli-usersjs"
    restart: always
    ports:
      - "8090:80" # <Port exposed> : <MySQL Port running inside container>
    networks:
      - proxy
      - default

networks:
  proxy:
    external:
      name: nginx-proxy
