name: Deploy Static Web SiteGitHub
run-name: ${{ github.actor }} is Deploying on GitHub Actions 🚀
on: [push]

jobs:
  Job1:
    name: Push Compose File to Deploy Server
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.read-file.outputs.version }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set Version for Image generation in job2
        id: read-file
        run: |
          output=`cat version.txt`
          echo version=$output >> $GITHUB_OUTPUT

      #      - name: Get Version
      #        run: |
      #          echo "Your version : ${{ steps.read-file.outputs.version }} "

      - name: Create Directory on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            mkdir -p ~/project/usersjs

      - name: Copy docker-compose.yml to Dir
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "docker-compose.yml"
          target: ~/project/usersjs

  Job2:
    name: Build and Generate Image
    runs-on: ubuntu-latest
    needs: Job1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      #- name: Set up JDK 22.0
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: microsoft
      #     java-version: 21

      #- name: unit Test
      #   run: Unit Test --file pom.xml

      #- name: Build the application
      #   run: |
      #   mvn clean
      #   mvn - B package --file pom.xml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx/Image
        uses: docker/setup-buildx-action@v3

      - name: Loging to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v6
        env:
          OUTPUT1: ${{needs.Job1.outputs.output1}}
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/usersjs:${{needs.Job1.outputs.output1}}
  #          tags: ${{secrets.DOCKER_USERNAME}}/app:${{github.run_attempt}}

  Job3:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [Job1, Job2]
    steps:
      - name: Lauch Image
        uses: appleboy/ssh-action@master
        env:
          OUTPUT1: ${{needs.Job1.outputs.output1}}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/project/usersjs
            docker compose down -t 0 -v --rmi 'all'
            rm -f *.env
            echo "TAG=${{needs.Job1.outputs.output1}}" >> .env
            docker compose up -d
